In [1]:
import torch 
import transformers

In [24]:
from transformers import AutoModelForQuestionAnswering, AutoTokenizer, pipeline

model_name = "deepset/roberta-base-squad2"

# a) Get predictions
nlp = pipeline('question-answering', model=model_name, tokenizer=model_name)
QA_input = {
    'question': 'Why is model conversion important?',
    'context': 'The option to convert models between FARM and transformers gives freedom to the user and let people easily switch between frameworks.'
}
res = nlp(QA_input)

# b) Load model & tokenizer
model = AutoModelForQuestionAnswering.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)

In [25]:
print(res)

{'score': 0.21171414852142334, 'start': 59, 'end': 84, 'answer': 'gives freedom to the user'}


In [27]:
from transformers import AutoModelForQuestionAnswering, AutoTokenizer, pipeline

model_name = "deepset/roberta-base-squad2"

# a) Get predictions
nlp = pipeline('question-answering', model=model_name, tokenizer=model_name)
QA_input = {
    'question': 'Which part of a tree can have vertical or horizontal variation in its specific gravity?',
    'context': 'Age, diameter, height, radial growth, geographical location, site and growing conditions, silvicultural treatment, and seed source, all to some degree influence wood density. Variation is to be expected. Within an individual tree, the variation in wood density is often as great as or even greater than that between different trees (Timell 1986). Variation of specific gravity within the bole of a tree can occur in either the horizontal or vertical direction.'
}
res = nlp(QA_input)

# b) Load model & tokenizer
model = AutoModelForQuestionAnswering.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)

print(res)

{'score': 0.490986704826355, 'start': 388, 'end': 392, 'answer': 'bole'}


In [2]:
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

tokenizer = AutoTokenizer.from_pretrained("gpt2")
model = AutoModelForCausalLM.from_pretrained("gpt2")

prompt = "Today I believe we can finally"
input_ids = tokenizer(prompt, return_tensors="pt").input_ids

# sample up to 30 tokens
torch.manual_seed(0)
outputs = model.generate(input_ids, do_sample=True, max_length=30)
tokenizer.batch_decode(outputs, skip_special_tokens=True)
['Today I believe we can finally get rid of discrimination," said Rep. Mark Pocan (D-Wis.).\n\n"Just look at the']

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


['Today I believe we can finally get rid of discrimination," said Rep. Mark Pocan (D-Wis.).\n\n"Just look at the']

In [3]:
# model generate max 30 tokens and temperature 0.7 and top_p 0.9
torch.manual_seed(0)
prompt = "It is important for all countries to try harder to reduce carbon emissions because"
input_ids = tokenizer(prompt, return_tensors="pt").input_ids

outputs = model.generate(input_ids, do_sample=True, max_length=30,top_p=0.9, temperature=0.7)
tokenizer.batch_decode(outputs, skip_special_tokens=True)
# It is important for all countries to try harder to reduce carbon emissions because it is a very big problem in the world today," he said.\n\n

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


['It is important for all countries to try harder to reduce carbon emissions because it is a very big problem in the world today," he said.\n\n']

In [30]:
# model generate max 30 tokens and temperature 0.8 and top_p 0.8
torch.manual_seed(0)
prompt = "It is important for all countries to try harder to reduce carbon emissions because"
input_ids = tokenizer(prompt, return_tensors="pt").input_ids

outputs = model.generate(input_ids, do_sample=True, max_length=30,top_p=0.8, temperature=0.8)
tokenizer.batch_decode(outputs, skip_special_tokens=True)
# ['It is important for all countries to try harder to reduce carbon emissions because this is the only way to tackle climate change," he said.\n\n"']

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


['It is important for all countries to try harder to reduce carbon emissions because this is the only way to tackle climate change," he said.\n\n"']

In [6]:
# output the probabilities of the each word that is generated.
torch.manual_seed(0)
prompt = "It is important for all countries to try harder to reduce carbon emissions because"
input_ids = tokenizer(prompt, return_tensors="pt").input_ids

outputs = model.generate(input_ids, max_length=30,top_p=0.1, temperature=1.0, return_dict_in_generate=True, output_scores=True)
tokenizer.batch_decode(outputs.sequences, skip_special_tokens=True)

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


['It is important for all countries to try harder to reduce carbon emissions because it is a key part of the global economy.\n\n"We need to']

In [8]:
print(outputs)

GreedySearchDecoderOnlyOutput(sequences=tensor([[1026,  318, 1593,  329,  477, 2678,  284, 1949, 7069,  284, 4646, 6588,
         8971,  780,  340,  318,  257, 1994,  636,  286,  262, 3298, 3773,   13,
          198,  198,    1, 1135,  761,  284]]), scores=(tensor([[-126.3008, -125.6421, -133.5102,  ..., -132.7888, -133.6604,
         -127.7045]]), tensor([[-132.1247, -130.5210, -138.0126,  ..., -140.9460, -139.2059,
         -132.6104]]), tensor([[-135.8139, -135.3814, -143.6343,  ..., -143.6512, -141.7850,
         -138.9233]]), tensor([[-147.2896, -145.7075, -151.7347,  ..., -157.4900, -153.2661,
         -148.2787]]), tensor([[-113.9601, -111.4267, -118.7147,  ..., -121.8256, -122.8286,
         -116.0324]]), tensor([[-61.5197, -57.9800, -64.9529,  ..., -70.8180, -72.1236, -62.2383]]), tensor([[-108.9445, -106.4659, -111.8005,  ..., -116.4430, -115.6365,
         -108.9539]]), tensor([[-140.2385, -137.1673, -141.4753,  ..., -145.5077, -148.0972,
         -139.7022]]), tensor([[-140

In [47]:
# Modify the code to output the probabilities of the each word that is generated. You’ll need to set these two generate parameters:return_dict_in_generate=True and, output_scores=True, and extract the probabilities that come in the returned dictionary one call at a time. 

# output the probabilities of the each word that is generated.
torch.manual_seed(0)
prompt = "It is important for all countries to try harder to reduce carbon emissions because"
input_ids = tokenizer(prompt, return_tensors="pt").input_ids

outputs = model.generate(input_ids, max_length=25,top_p=1.0, temperature=0.6, return_dict_in_generate=True, output_scores=True)
tokenizer.batch_decode(outputs.sequences, skip_special_tokens=True)

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


['It is important for all countries to try harder to reduce carbon emissions because it is a key part of the global economy.\n']

In [48]:
# probabilities of the each word that is generated.
outputs.keys()

odict_keys(['sequences', 'scores'])

In [9]:
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

tokenizer = AutoTokenizer.from_pretrained("gpt2")
model = AutoModelForCausalLM.from_pretrained("gpt2")

torch.manual_seed(0)
prompt = "It is important for all countries to try harder to reduce carbon emissions because"
input_ids = tokenizer(prompt, return_tensors="pt").input_ids

# output the probabilities of the each word that is generated. You’ll need to set these two generate parameters:return_dict_in_generate=True and, output_scores=True, and extract the probabilities that come in the returned dictionary one call at a time.
outputs = model.generate(input_ids, max_length=25,top_p=0.1, temperature=1.0, return_dict_in_generate=True, output_scores=True, do_sample=True)
tokenizer.batch_decode(outputs.sequences, skip_special_tokens=True)

# probabilities of the each word that is generated.
outputs.scores

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


(tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]]),
 tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]]),
 tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]]),
 tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]]),
 tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]]),
 tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]]),
 tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]]),
 tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]]),
 tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]]),
 tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]]),
 tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]]))

In [11]:
print(outputs)

SampleDecoderOnlyOutput(sequences=tensor([[1026,  318, 1593,  329,  477, 2678,  284, 1949, 7069,  284, 4646, 6588,
         8971,  780,  340,  318,  257, 1994,  636,  286,  262, 3298, 3773,   13,
          198]]), scores=(tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]]), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]]), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]]), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]]), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]]), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]]), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]]), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]]), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]]), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]]), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]])), attentions=None, hidden_states=None)


In [46]:
# Generate the tree for the above sequence as input, providing the top 3 probabilities for each word position
probabilities = outputs.scores

IndexError: index 1 is out of bounds for dimension 0 with size 1